FROM golang:1.21-alpine AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/ cmd/
COPY pkg/ pkg/

RUN go build -o /bin/node ./cmd/node

FROM alpine:3.19

WORKDIR /app

COPY --from=build /bin/node /app/node

EXPOSE 8000

ENTRYPOINT ["/app/node"]
